### PR TITLE
do not remove-and-add file from watcher when event happens

### LINKED ISSUE #6: bug: WRITE events are missed on Mac OS arm64
#### Description

On Mac OS arm64 (14" 2021 Macbook Pro, M1 Pro), `fsnotify` sends two events when a file changes: `CHMOD` and `WRITE`. When the first event `CHMOD` comes in, `w.Remove(event.Name)` and `w.Add(event.Name)` are called [here](https://github.com/gobuffalo/refresh/blob/a8045bef5bf626f6c6cdbfd9128bfa888da40c59/refresh/manager.go#L57-L58). This causes the second `WRITE` event to sometimes not trigger a build (possibly some race condition). I am not sure what is causing this, and it is not clear why the Remove and Add is necessary on each event. If the Remove() and Add() lines are commented out, the build refreshes and works as expected when a file changes, every time.

#### Expected Behavior

`build()` is called every time a file changes.

#### Actual Behavior

When a file changes, only some times a build will trigger.

### To Reproduce

1. Create a new buffalo project with `buffalo new`
2. Run `buffalo dev`
3. Edit and save a file in `actions/` multiple times and watch for rebuilds of the app.

### Additional Context

Details

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /usr/local/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.18.7, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /Users/saurori/Documents/dev/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /opt/homebrew/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v18.10.0, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /opt/homebrew/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 8.19.2, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /opt/homebrew/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✘ Your version of Yarn, 4.0.0-rc.25, does not meet the minimum requirements.

Minimum versions of Yarn are:

* >=1.12

For help setting up your Yarn environment please follow the instructions for you platform at:

https://yarnpkg.com/en/docs/install

-> PostgreSQL: Checking installation
✓ The `postgres` executable was found on your system at: /opt/homebrew/bin/postgres

-> PostgreSQL: Checking minimum version requirements
✓ Your version of PostgreSQL, 14.5.0, meets the minimum requirements.

-> MySQL: Checking installation
✘ The `mysql` executable could not be found on your system.
For help setting up your MySQL environment please follow the instructions for you platform at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.37.0, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /Users/saurori/Documents/dev/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.18.7, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /Users/saurori/Documents/dev/src/github.com/saurori/gobuffalo/coke
Root        /Users/saurori/Documents/dev/src/github.com/saurori/gobuffalo/coke
GoPath      /Users/saurori/Documents/dev
PackagePkg  coke
ActionsPkg  coke/actions
ModelsPkg   coke/models
GriftsPkg   coke/grifts
WithModules true
Name        coke
Bin         bin/coke
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack --mode production --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "coke"
bin = "bin/coke"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v3@latest"

-> Buffalo: go.mod
module coke

go 1.17

require (
        github.com/gobuffalo/buffalo v1.0.1
        github.com/gobuffalo/buffalo-pop/v3 v3.0.6
        github.com/gobuffalo/envy v1.10.2
        github.com/gobuffalo/grift v1.5.2
        github.com/gobuffalo/mw-csrf v1.0.1
        github.com/gobuffalo/mw-forcessl v1.0.1
        github.com/gobuffalo/mw-i18n/v2 v2.0.2
        github.com/gobuffalo/mw-paramlogger v1.0.1
        github.com/gobuffalo/pop/v6 v6.0.8
        github.com/gobuffalo/suite/v4 v4.0.3
        github.com/unrolled/secure v1.13.0
)

require (
        github.com/BurntSushi/toml v1.2.0 // indirect
        github.com/Masterminds/semver/v3 v3.1.1 // indirect
        github.com/aymerick/douceur v0.2.0 // indirect
        github.com/davecgh/go-spew v1.1.1 // indirect
        github.com/dustin/go-humanize v1.0.0 // indirect
        github.com/fatih/color v1.13.0 // indirect
        github.com/fatih/structs v1.1.0 // indirect
        github.com/felixge/httpsnoop v1.0.3 // indirect
        github.com/fsnotify/fsnotify v1.6.0 // indirect
        github.com/go-sql-driver/mysql v1.6.0 // indirect
        github.com/gobuffalo/events v1.4.3 // indirect
        github.com/gobuffalo/fizz v1.14.4 // indirect
        github.com/gobuffalo/flect v0.3.0 // indirect
        github.com/gobuffalo/github_flavored_markdown v1.1.3 // indirect
        github.com/gobuffalo/helpers v0.6.7 // indirect
        github.com/gobuffalo/httptest v1.5.2 // indirect
        github.com/gobuffalo/logger v1.0.7 // indirect
        github.com/gobuffalo/meta v0.3.3 // indirect
        github.com/gobuffalo/nulls v0.4.2 // indirect
        github.com/gobuffalo/plush/v4 v4.1.16 // indirect
        github.com/gobuffalo/refresh v1.13.2 // indirect
        github.com/gobuffalo/tags/v3 v3.1.4 // indirect
        github.com/gobuffalo/validate/v3 v3.3.3 // indirect
        github.com/gofrs/uuid v4.3.0+incompatible // indirect
        github.com/gorilla/css v1.0.0 // indirect
        github.com/gorilla/handlers v1.5.1 // indirect
        github.com/gorilla/mux v1.8.0 // indirect
        github.com/gorilla/securecookie v1.1.1 // indirect
        github.com/gorilla/sessions v1.2.1 // indirect
        github.com/inconshreveable/mousetrap v1.0.1 // indirect
        github.com/jackc/chunkreader/v2 v2.0.1 // indirect
        github.com/jackc/pgconn v1.13.0 // indirect
        github.com/jackc/pgio v1.0.0 // indirect
        github.com/jackc/pgpassfile v1.0.0 // indirect
        github.com/jackc/pgproto3/v2 v2.3.1 // indirect
        github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b // indirect
        github.com/jackc/pgtype v1.12.0 // indirect
        github.com/jackc/pgx/v4 v4.17.2 // indirect
        github.com/jmoiron/sqlx v1.3.5 // indirect
        github.com/joho/godotenv v1.4.0 // indirect
        github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
        github.com/luna-duclos/instrumentedsql v1.1.3 // indirect
        github.com/mattn/go-colorable v0.1.13 // indirect
        github.com/mattn/go-isatty v0.0.16 // indirect
        github.com/mattn/go-sqlite3 v1.14.15 // indirect
        github.com/microcosm-cc/bluemonday v1.0.21 // indirect
        github.com/mitchellh/go-homedir v1.1.0 // indirect
        github.com/monoculum/formam v3.5.5+incompatible // indirect
        github.com/nicksnyder/go-i18n v1.10.1 // indirect
        github.com/pelletier/go-toml v1.9.5 // indirect
        github.com/pkg/errors v0.9.1 // indirect
        github.com/pmezard/go-difflib v1.0.0 // indirect
        github.com/rogpeppe/go-internal v1.9.0 // indirect
        github.com/sergi/go-diff v1.2.0 // indirect
        github.com/sirupsen/logrus v1.9.0 // indirect
        github.com/sourcegraph/annotate v0.0.0-20160123013949-f4cad6c6324d // indirect
        github.com/sourcegraph/syntaxhighlight v0.0.0-20170531221838-bd320f5d308e // indirect
        github.com/spf13/cobra v1.6.0 // indirect
        github.com/spf13/pflag v1.0.5 // indirect
        github.com/stretchr/testify v1.8.0 // indirect
        golang.org/x/crypto v0.0.0-20221012134737-56aed061732a // indirect
        golang.org/x/net v0.0.0-20221014081412-f15817d10f9b // indirect
        golang.org/x/sync v0.0.0-20220929204114-8fcdb60fdcc0 // indirect
        golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43 // indirect
        golang.org/x/term v0.0.0-20220919170432-7a66f970e087 // indirect
        golang.org/x/text v0.3.8 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

</details>

### PR DESCRIPTION
**Pull request by sio4**
Removing `Remove()` and `Add()` calls when an event happens on a file to prevent missing events.

See details at https://github.com/gobuffalo/refresh/issues/6#issuecomment-1279670147

(only the first commit a1e9e9c is for fixing the issue, others are code clean up)

fixes #6

### CODE REVIEW

**Review by saurori — APPROVED** [review]

File: refresh/manager.go [hunk 1]
```diff
@@ -54,8 +54,6 @@ func (r *Manager) Start() error {
 					if event.Op != fsnotify.Chmod {
```
Comment (arp242) [inline refresh/manager.go:54]: You should use `event.Has(fsnotify.Chmod)` here; in some (rare) cases there can be multiple events.

Unrelated to this PR really, but just something I noticed.

Comment (sio4) [reply refresh/manager.go:54]: Thanks for the comment. However, the answer is no.

The fancy method `Has()` was introduced from v1.6.0 of fsnotify and it should be used when we just want to check if the value has a specific bit, regardless of other bits. In that case, your suggestion is correct.

However, the logic is that the following `build()` should be prevented when only `CHMOD` happen without any events indicating a real change. For example, if the value is `CHMOD|WRITE`, which has `CHMOD` along with `WRITE`, we should run `build()` and check with `Has()` here is not correct in this case.

Comment (sio4) [reply refresh/manager.go:54]: I missed adding this code comment when I upgraded fsnotify to v1.6.0 to prevent possible future confusion.

Comment (sio4) [reply refresh/manager.go:54]: One quick question. Do you have any plan to support `HasNot()` or similar?

Comment (arp242) [reply refresh/manager.go:54]: CHMOD | WRITE could indicate there was a write and a chmod though; in that case I think you'll want to do a rebuild?

I don't think I've ever seen that happen though, so it's a really hypothetical issue and probably not worth worrying about one way or the other.

Comment (arp242) [reply refresh/manager.go:54]: Sorry, I didn't see your further comments.

> when I upgrade fsnotify to v1.6.0

You updated it in this PR.

> One quick question. Do you have any plan to support HasNot() or similar?

Not really; I think !Has() should be good enough? I try to keep the API as small as possible, as I usually find that easier to use (less documentation, less stuff in completion, etc.)

Comment (sio4) [reply refresh/manager.go:54]: Yes, Refresh rebuilds the supporting app in any of the other cases except CHMOD only. What is the possible case then? (CHMOD with which?)

Comment (saurori) [reply refresh/manager.go:54]: I saw one `CHMOD | WRITE` event when I was testing for the bug other day. So it can happen.

Comment (arp242) [reply refresh/manager.go:54]: On Linux chmod gets sent if a file is unlinked (removed) while there are still open file descriptors. There may be some other caveats too (for example kqueue used by macOS and BSD isn't very well documented on this).

It's actually pretty tricky to determine "did this file change?" reliably; the general strategy I've used is watch the parent directory of the file you want to watch, watch for Create and Write events, and debounce the events by 100ms to make sure the write is finished (there's an example of that in `./cmd/fsnotify`).`

That's the most reliable way I've figured out so far that works well on all platforms in all situations as far as I know. Things are better in v1.6.0 than they used to be in older versions though.

Comment (sio4) [reply refresh/manager.go:54]: > > One quick question. Do you have any plan to support HasNot() or similar?
> 
> Not really; I think !Has() should be good enough? I try to keep the API as small as possible, as I usually find that easier to use (less documentation, less stuff in completion, etc.)

Agree. `Has()` could be enough for most usages and `HasNot()` will not be popular I guess (so for the edge case like this, we can still use bit operation or just compare with a value). However, `!Has(A)` is not equal to `HasNot(A)`.

Comment (sio4) [reply refresh/manager.go:54]: if the CHMOD event can be delivered with the other, including write, remove, or something else, we should not filter them out so the current logic should check CHMOD-only event. If there is no `HasNot()` API, `!= CHMOD` is correct here.

Comment (sio4) [reply refresh/manager.go:54]: anyway, nice to e-meet you @arp242!

Comment (sio4) [reply refresh/manager.go:54]: > However, `!Has(A)` is not equal to `HasNot(A)`.

(Oh, this is not literally true but I mean in this context.)
